name: Promote Tag and Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to promote"
        required: true
      next_step:
        description: "Next step in promotion (e.g., staging, production)"
        required: true

jobs:
  promote-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Promote Git Tag to Next Step
        id: promote
        run: |
          TAG=${{ github.event.inputs.tag }}
          NEXT_STEP=${{ github.event.inputs.next_step }}
          NEW_TAG="${TAG}-${NEXT_STEP}"

          echo "Promoting tag $TAG to $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Output New Tag
        run: echo "New tag promoted: ${{ steps.promote.outputs.new_tag }}"

  confirm-deploy:
    runs-on: ubuntu-latest
    needs: promote-tag
    if: ${{ github.event.inputs.next_step == 'staging' || github.event.inputs.next_step == 'production' }}
    steps:
      - name: Manual Approval for Deployment
        uses: peter-evans/slash-command-dispatch@v2
        with:
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: workflow
          dispatch-type: message
          command: "/deploy"
          permission: write
          args: |
            Do you want to deploy to the ${{ github.event.inputs.next_step }} environment? Reply with /deploy to confirm.

      - name: Deploy to Next Step
        if: success()
        run: |
          echo "Deploying to ${{ github.event.inputs.next_step }}"
          # Add your deployment logic here, for example:
          # ./deploy.sh ${{ github.event.inputs.next_step }}
